# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 08d22a00a69f157dc019c6f23286d5249a6673165cc5e0026ce92bc8dbe3b3aa5d2d7d1f55319cdceb2d281268d43878fdae4e9b5f121048a29b13b688b47707

test:
  secret_key_base: 56f5d1428330b1539d5e26e623dfc0cac7f54dfe8561e7ad72bca1f7f41a919062052fab764eea5056976e6c6556b716d05cd1c45bb6e7694c131efa5918e07a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
